# Generated by Django 5.2 on 2025-05-25 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ['order'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['resource_type', 'title'], 'verbose_name': 'Ressource', 'verbose_name_plural': 'Ressources'},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Icône Bootstrap Icons (ex: bi-egg-fried)', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_weeks',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Durée (semaines)'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Mise en avant'),
        ),
        migrations.AddField(
            model_name='course',
            name='static_image_path',
            field=models.CharField(blank=True, help_text="Chemin relatif dans static/img/ (ex: 'courses/cuisine.jpg')", max_length=255, verbose_name='Chemin image statique'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='duration_hours',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Durée (heures)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien externe'),
        ),
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/files/', verbose_name='Fichier joint'),
        ),
        migrations.AddField(
            model_name='resource',
            name='static_image_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Chemin image statique'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='front.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detailed_description',
            field=models.TextField(verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Image uploadée'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Formateur'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FG)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_enrolled', to=settings.AUTH_USER_MODEL, verbose_name='Étudiants inscrits'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='front.course', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='front.course', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('INGREDIENTS', 'Ingrédients Clés'), ('CERTIFICATION', 'Certification'), ('COMMUNITY', 'Communauté'), ('TOOLS', 'Ressources'), ('RECIPE', 'Fiche recette')], max_length=20, verbose_name='Type de ressource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='front_cours_slug_9dd267_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='front_cours_created_8844f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_module_order'),
        ),
    ]
