"""
Django settings for gandalhub project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# === BASE CONFIGURATION ===
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-+pexfp+nvz)ors1ug@_0wfto5ssk&+!-4z83*hzl*(&1o6ve)i'

DEBUG = True

ALLOWED_HOSTS = []

# === APPLICATIONS ===
INSTALLED_APPS = [
    # Applications locales
    'front',
    'quiz',

    # Applications Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Applications tierces
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'social_django',
]

# === MIDDLEWARE ===
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

# === AUTHENTICATION BACKENDS ===
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# === SITE CONFIGURATION ===
SITE_ID = 1

# === SOCIAL AUTH CONFIGURATION ===
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '741399796382-vvot5vc6i8lm53afkfoj10i3qhps3r9e.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

# === URL CONFIGURATION ===
ROOT_URLCONF = 'gandalhub.urls'
ACCOUNT_FORMS = {
    'signup': 'front.forms.CustomSignupForm',  # ✅ chemin absolu correct
}



# === TEMPLATES CONFIGURATION ===
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates/front'],  # Assurez-vous que le dossier "templates" existe
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # Nécessaire pour Django Allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# === WSGI APPLICATION ===
WSGI_APPLICATION = 'gandalhub.wsgi.application'

# === DATABASE CONFIGURATION ===
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# === PASSWORD VALIDATION ===
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# === INTERNATIONALIZATION ===
LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# === STATIC FILES CONFIGURATION ===
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'front/static'),
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# === REDIRECTION CONFIGURATION ===
LOGIN_REDIRECT_URL = '/'  # Redirige après connexion
ACCOUNT_LOGOUT_REDIRECT_URL = '/'  # Redirige après déconnexion
LOGIN_URL = '/'  # URL de connexion
LOGOUT_REDIRECT_URL = '/'  # Redirige après déconnexion

# === DEFAULT PRIMARY KEY FIELD TYPE ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# === EMAIL CONFIGURATION ===
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'votre_adresse_email@gmail.com'
EMAIL_HOST_PASSWORD = 'votre_mot_de_passe'


